---

AWSTemplateFormatVersion: "2010-09-09"
Description: A CFN template to create an incoming data s3 bucket and outgoing processed S3 bucket

Resources:
  IncomingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-incoming-data-bucket-${AWS::Region}
      NotificationConfiguration:
          QueueConfigurations:
               - Event: s3:ObjectCreated:*
                 Queue: !GetAtt IncomingFileSQS.Arn

  OutgoingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-outgoing-data-bucket-${AWS::Region}


  
  #S3 event trigger
  #lambda

Outputs:
  IncomingBucketName:
    Description: "Landing Bucket for NYC Taxi Trip Data"
    Value: !Ref IncomingBucket

  OutgoingBucketName:
    Description: "Processed Parquet Taxi Trip Data Bucket"
    Value: !Ref OutgoingBucket
  
  QueueURL:
    Description: URL of IncomingFileSQS
    Value:
      Ref: IncomingFileSQS
  QueueARN:
    Description: ARN of IncomingFileSQS
    Value:
      Fn::GetAtt:
      - IncomingFileSQS
      - Arn
  QueueName:
    Description: Name of IncomingFileSQS
    Value:
      Fn::GetAtt:
      - IncomingFileSQS
      - QueueName
