---

AWSTemplateFormatVersion: "2010-09-09"
Description: A CFN template to create an incoming file sqs

Parameters:
  DelaySeconds:
    Description: Time delay for delivery of messages in queue.
    Type: Number
    Default: '5'
  MaximumMessageSize:
    Description: Size of message in queue in bytes
    Type: Number
    Default: '262144' #262KB
  MessageRetentionPeriod:
    Description: Number of seconds the message is retained in the queue
    Type: Number
    Default: '345600'

Resources:
     IncomingFileSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "IncomingFileSQS"
        DelaySeconds:
          Ref: DelaySeconds
        MaximumMessageSize:
          Ref: MaximumMessageSize
        MessageRetentionPeriod: 
          Ref: MessageRetentionPeriod
